name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
    - uses: actions/checkout@v3
    
    # Build Server
    - name: Build Server
      run: |
        cd server
        npm ci
        npm run build
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}

    # Build Client
    - name: Build Client
      run: |
        cd client
        npm ci
        npm run build
      env:
        REACT_APP_API_URL: ${{ secrets.API_URL }}
        REACT_APP_GOOGLE_SPREADSHEET_ID: ${{ secrets.GOOGLE_SPREADSHEET_ID }}

    # Test Server
    - name: Test Server
      run: |
        cd server
        npm test

    # Test Client
    - name: Test Client
      run: |
        cd client
        npm test

    # Deploy
    - name: Deploy
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          server/dist
          client/build
